### ISSUE TITLE
`miral-app` does not confine the pointer properly when running fullscreen games (e.g. counter strike 2)

### ISSUE THREAD

**Issue by mattkae** [canonical/mir#3436] opened 2024-06-20 17:51 UTC
## Repro
1. Open up counter strike in fullscreen mode
2. Boot into a match
3. Move the cursor around and note that you run into a wall at the edges of the screen

## Expectation
The cursor can be moved infinitely so that you can properly look at the screen

## Notes
- This doe **NOT** happen on Miriway, however it seems that the Policy isn't at fault

**Comment by Saviq** [comment] 2024-06-21 07:55
Hmm isn't that this?
- https://github.com/canonical/mir/issues/1442

In which case, should it work properly anywhere? Is CS even using Wayland and the confinement protocol/

**Comment by AlanGriffiths** [comment] 2024-06-21 08:03
You can enable `zwp_pointer_constraints_v1` and `zwp_relative_pointer_manager_v1` to get the behaviour you expect.

IIRC these are not enabled by default as the Mir implementation is incomplete (and caused problems with electron apps).

Closing as a duplicate of #1442

**Closed by AlanGriffiths** 2024-06-21 08:03 UTC
Labels: bug

**Comment by mattkae** [comment] 2024-06-21 11:14
> You can enable `zwp_pointer_constraints_v1` and `zwp_relative_pointer_manager_v1` to get the behaviour you expect.
> 
> IIRC these are not enabled by default as the Mir implementation is incomplete (and caused problems with electron apps).
> 
> Closing as a duplicate of #1442

@Saviq and @AlanGriffiths:

This doesn't explain why the behaviour is correct on Miriway but incorrect on miral-shell and others. Also, counter strike is using X11, not Wayland.

**Comment by AlanGriffiths** [comment] 2024-06-21 11:25
> This doesn't explain why the behaviour is correct on Miriway but incorrect on miral-shell and others. Also, counter strike is using X11, not Wayland.

It does: Miriway doesn't use the Mir defaults for enabling these protocols

**Comment by mattkae** [comment] 2024-06-21 11:37
> > This doesn't explain why the behaviour is correct on Miriway but incorrect on miral-shell and others. Also, counter strike is using X11, not Wayland.
> 
> It does: Miriway doesn't use the Mir defaults for enabling these protocols

You are right! I take it back :+1:
