### ISSUE TITLE
The lockscreen surface respects exclusion zones

### ISSUE THREAD

**Issue by mattkae** [canonical/mir#3265] opened 2024-03-04 21:36 UTC
## Repro
- Have a couple of shell components in your shell (e.g. waybar)
- Start a lockscreen and note that the area where the shell component was rendered is now black and the lockscreen will not overwrite it

**Comment by AlanGriffiths** [comment] 2024-03-05 08:17
Duplicate of #1992 (and #3125)

**Closed by AlanGriffiths** 2024-03-05 08:17 UTC
Labels: bug
