### ISSUE TITLE
update_from_hardware_state throws away existing gamma state

### ISSUE THREAD

**Issue by RAOF** [canonical/mir#3510] opened 2024-07-26 04:54 UTC
See here:
https://github.com/canonical/mir/blob/c317ba04260d80cc1a233cb093c9aa0a9695cb79/src/platforms/gbm-kms/server/kms/real_kms_output.cpp#L559-L564

If the current configuration already had a gamma table set, this would replace it with a blank (linear) gamma.

**Comment by AlanGriffiths** [comment] 2024-07-30 15:14
Duplicate of #3253

**Closed by AlanGriffiths** 2024-07-30 15:14 UTC
